spring.application.name=NewRelicPatrones
management.newrelic.metrics.export.enabled=false
spring.datasource.url=jdbc:mysql://newrelicdb.mysql.database.azure.com:3306/parcial
spring.datasource.username=newrelic
spring.datasource.password=Patrones123
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.hikari.maximum-pool-size=10
