spring.application.name=NewRelicPatrones
management.newrelic.metrics.export.enabled=false
spring.datasource.url=jdbc:mysql://newrelicerca.mysql.database.azure.com:3306/parcial
spring.datasource.username=newrelic
spring.datasource.password=Patrones123
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=30
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariCP
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari=TRACE
